CREATE SCHEMA IF NOT EXISTS test_inventory_v1;

CREATE TABLE IF NOT EXISTS test_inventory_v1.product (
  id UUID PRIMARY KEY NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ,
  name TEXT NOT NULL,
  price BIGINT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('PRODUCT_STATUS_UNSPECIFIED', 'PRODUCT_STATUS_ACTIVE', 'PRODUCT_STATUS_ARCHIVED'))
);
