version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go fmt ./...
    - go test ./...

builds:
  - main: cmd/protoc-gen-clarity/main.go
    id: protoc-gen-clarity
    binary: protoc-gen-clarity
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

  - main: cmd/clarity-lint-plugin/main.go
    id: clarity-lint-plugin
    binary: clarity-lint-plugin
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - id: protoc-gen-clarity
    builds: [protoc-gen-clarity]
    formats: [tar.gz]
    name_template: >-
      protoc-gen-clarity_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

  - id: clarity-lint-plugin
    builds: [clarity-lint-plugin]
    formats: [tar.gz]
    name_template: >-
      clarity-lint-plugin_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
