// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: clarity/plugin/v1/options.proto

package pluginV1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_ENTITY      Role = 1
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_ENTITY",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_ENTITY":      1,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_clarity_plugin_v1_options_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_clarity_plugin_v1_options_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_clarity_plugin_v1_options_proto_rawDescGZIP(), []int{0}
}

type ClarityMessageOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role Role `protobuf:"varint,1,opt,name=role,proto3,enum=clarity.plugin.v1.Role" json:"role,omitempty"`
}

func (x *ClarityMessageOptions) Reset() {
	*x = ClarityMessageOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_clarity_plugin_v1_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClarityMessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClarityMessageOptions) ProtoMessage() {}

func (x *ClarityMessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_clarity_plugin_v1_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClarityMessageOptions.ProtoReflect.Descriptor instead.
func (*ClarityMessageOptions) Descriptor() ([]byte, []int) {
	return file_clarity_plugin_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *ClarityMessageOptions) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

var file_clarity_plugin_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*ClarityMessageOptions)(nil),
		Field:         50001,
		Name:          "clarity.plugin.v1.message",
		Tag:           "bytes,50001,opt,name=message",
		Filename:      "clarity/plugin/v1/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional clarity.plugin.v1.ClarityMessageOptions message = 50001;
	E_Message = &file_clarity_plugin_v1_options_proto_extTypes[0]
)

var File_clarity_plugin_v1_options_proto protoreflect.FileDescriptor

var file_clarity_plugin_v1_options_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x63, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x11, 0x63, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x15, 0x43, 0x6c, 0x61, 0x72, 0x69, 0x74,
	0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x2b, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e,
	0x63, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x2a, 0x2d, 0x0a, 0x04,
	0x52, 0x6f, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x4f,
	0x4c, 0x45, 0x5f, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x10, 0x01, 0x3a, 0x65, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd1, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x28, 0x2e, 0x63, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6c, 0x61, 0x62, 0x73, 0x65, 0x74, 0x2f, 0x63, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x2d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x63, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x56, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_clarity_plugin_v1_options_proto_rawDescOnce sync.Once
	file_clarity_plugin_v1_options_proto_rawDescData = file_clarity_plugin_v1_options_proto_rawDesc
)

func file_clarity_plugin_v1_options_proto_rawDescGZIP() []byte {
	file_clarity_plugin_v1_options_proto_rawDescOnce.Do(func() {
		file_clarity_plugin_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_clarity_plugin_v1_options_proto_rawDescData)
	})
	return file_clarity_plugin_v1_options_proto_rawDescData
}

var file_clarity_plugin_v1_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_clarity_plugin_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_clarity_plugin_v1_options_proto_goTypes = []interface{}{
	(Role)(0),                           // 0: clarity.plugin.v1.Role
	(*ClarityMessageOptions)(nil),       // 1: clarity.plugin.v1.ClarityMessageOptions
	(*descriptorpb.MessageOptions)(nil), // 2: google.protobuf.MessageOptions
}
var file_clarity_plugin_v1_options_proto_depIdxs = []int32{
	0, // 0: clarity.plugin.v1.ClarityMessageOptions.role:type_name -> clarity.plugin.v1.Role
	2, // 1: clarity.plugin.v1.message:extendee -> google.protobuf.MessageOptions
	1, // 2: clarity.plugin.v1.message:type_name -> clarity.plugin.v1.ClarityMessageOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clarity_plugin_v1_options_proto_init() }
func file_clarity_plugin_v1_options_proto_init() {
	if File_clarity_plugin_v1_options_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_clarity_plugin_v1_options_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClarityMessageOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_clarity_plugin_v1_options_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_clarity_plugin_v1_options_proto_goTypes,
		DependencyIndexes: file_clarity_plugin_v1_options_proto_depIdxs,
		EnumInfos:         file_clarity_plugin_v1_options_proto_enumTypes,
		MessageInfos:      file_clarity_plugin_v1_options_proto_msgTypes,
		ExtensionInfos:    file_clarity_plugin_v1_options_proto_extTypes,
	}.Build()
	File_clarity_plugin_v1_options_proto = out.File
	file_clarity_plugin_v1_options_proto_rawDesc = nil
	file_clarity_plugin_v1_options_proto_goTypes = nil
	file_clarity_plugin_v1_options_proto_depIdxs = nil
}
