syntax = "proto3";

package labset.options.v1;

import "google/protobuf/descriptor.proto";

option go_package = "github.com/labset/protobuf-toolchain/api/labset/options/v1;optionsV1";

enum Role {
  ROLE_UNSPECIFIED = 0;
  ROLE_ENTITY = 1;
  ROLE_REFERENCE = 2;
}

enum Operation {
  OPERATION_UNSPECIFIED = 0;
  OPERATION_CREATE = 1;
  OPERATION_GET = 2;
  OPERATION_LIST = 3;
  OPERATION_UPDATE = 4;
  OPERATION_DELETE = 5;
}

enum Subscriber {
  SUBSCRIBER_UNSPECIFIED = 0;
  SUBSCRIBER_AUDIT = 1;
  SUBSCRIBER_INDEX = 2;
  SUBSCRIBER_WEBHOOK = 3;
  SUBSCRIBER_NOTIFICATION = 4;
}

message LabsetMessageOptions {
  Role role = 1;
  repeated Operation operations = 2;
  repeated Subscriber subscribers = 3;
}

message LabsetFieldOptions {
  bool foreign_key = 1;
}

extend google.protobuf.MessageOptions {
  LabsetMessageOptions message = 60001;
}

extend google.protobuf.FieldOptions {
  LabsetFieldOptions field = 60002;
}
