// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: product.sql

package db

import (
	"context"

	uuid "github.com/gofrs/uuid/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO test_inventory_v1.product (
  id, created_at, updated_at, name, price, status
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, created_at, updated_at, deleted_at, name, price, status
`

type CreateProductParams struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Name      string
	Price     int64
	Status    string
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (TestInventoryV1Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Price,
		arg.Status,
	)
	var i TestInventoryV1Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Price,
		&i.Status,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM test_inventory_v1.product
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, created_at, updated_at, deleted_at, name, price, status
FROM test_inventory_v1.product
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (TestInventoryV1Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i TestInventoryV1Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Price,
		&i.Status,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, created_at, updated_at, deleted_at, name, price, status
FROM test_inventory_v1.product
WHERE deleted_at IS NULL
`

func (q *Queries) ListProducts(ctx context.Context) ([]TestInventoryV1Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestInventoryV1Product
	for rows.Next() {
		var i TestInventoryV1Product
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.Price,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsPaginated = `-- name: ListProductsPaginated :many
SELECT id, created_at, updated_at, deleted_at, name, price, status
FROM test_inventory_v1.product
WHERE deleted_at IS NULL
  AND ($1::uuid = '00000000-0000-0000-0000-000000000000'::uuid OR id > $1)
ORDER BY id
LIMIT $2
`

type ListProductsPaginatedParams struct {
	Cursor   uuid.UUID
	PageSize int32
}

func (q *Queries) ListProductsPaginated(ctx context.Context, arg ListProductsPaginatedParams) ([]TestInventoryV1Product, error) {
	rows, err := q.db.Query(ctx, listProductsPaginated, arg.Cursor, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestInventoryV1Product
	for rows.Next() {
		var i TestInventoryV1Product
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.Price,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :execrows
UPDATE test_inventory_v1.product
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE test_inventory_v1.product
SET name = $1, price = $2, status = $3, updated_at = NOW()
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, name, price, status
`

type UpdateProductParams struct {
	Name   string
	Price  int64
	Status string
	ID     uuid.UUID
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (TestInventoryV1Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.Price,
		arg.Status,
		arg.ID,
	)
	var i TestInventoryV1Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Price,
		&i.Status,
	)
	return i, err
}
